language: r
sudo: true
cache: packages
warnings_are_errors: true

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ppa'
    packages:
      - libmagick++-dev
      - libudunits2-dev
      - libproj-dev
      - libgeos-dev
      - libgdal-dev

before_install:
  - Rscript -e "remotes::install_github('ropensci/rrricanesdata')"
  - Rscript -e "remotes::install_github('ropensci/rnaturalearthhires')"

matrix:
  include:
  - r: oldrel
  - r: release
    after_success: Rscript -e "covr::codecov()"
    before_cache: Rscript -e "remotes::install_cran('pkgdown')"
    deploy:
      provider: script
      script:
        - Rscript -e ./data-raw/update-rrricanesdata.
        - Rscript -e "pkgdown::deploy_site_github(verbose = TRUE)"
        - git clone https://github.com/ropensci/rrricanesdata.git
        - cd rrricanesdata
        - GH_REPO="@github.com/$TRAVIS_REPO_SLUG.git"
        - FULL_REPO="https://$GH_TOKEN$GH_REPO"
        - Rscript -e ./data-raw/update.R
        - git add .
        - git commit -m 'Update data packages'
        - git push --force -quiet $FULL_REPO
      skip_cleanup: true
      on:
        all_branches: true
        condition: $TRAVIS_BRANCH =~ ^master|develop$
  - r: devel

env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false

env:
  global:
    secure: t3RJn4gGOnWDc2DSBOHwZ+DkLTZsmo2f9JDfg0H9ugzhZQFvXWy9/+HCak4t00aCpRojkMadqmQPORoeGCvzbdZV6Iu+ueFBb9JPD6CVgBiUYLcBL0aaYtPydKpw5EAFmvoHQo2J/p6bVtVvpBPOf+OVaeLqzcKFD8mxJtVl/sbSuZzCUKhs2KPIEtfpYZuchlZKRV6K+vrDomQytqQJeTlc5TTqY1VMOyY2E1eRgTxpTnN44caWSiqAmMkBx403TmFRpA0XZzsxxmUxTpXrNayT6S0qdn/VClyTTvJb/E92jFjm6c2MxCL6D5Xw7mv51srHf4qIxf3eLyj2ilZUKB4aNeecr5Y1/NeBgmx9K+WD16e9TJYOfR0J8i2HikBLgSgFCvU8D5p3sC6gI/+GCPBXyAEVcndnPUBCaRqfz4eeu3CkxiWgzWwabBoqjas/jp7gyOaj1lwEqOm+WNgA4E/7Klv161CXVHPLyvC7w/7mwVLK6PYN/6yyLAgGA8sumigSPxUvRSnzpDhBRaZH0/39pMFcY+XDjM0tVGj2ku/fdWwKHK8nwTEjNYVWGEjnFuJt9mGnacWOnyeEG9AAMvXYKrLkbKVWh+i4332F0YGqSmtzBn+2X9EQ753fujXd+s3jKkoKaYI58hb+A7BVPeVInDJOfDMmj6KklT6JFHM=
