# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

# Adapt as necessary starting from here

environment:
#  R_CHECK_ARGS: --no-build-vignettes --no-manual --no-tests # Disable tests due to issues w/ NHC archives.
  global:
    WARNINGS_ARE_ERRORS: 1

  matrix:
  - R_VERSION: oldrel
    RTOOLS_VERSION: 333
    CRAN: http://cran.rstudio.com

  - R_VERSION: oldrel
    RTOOLS_VERSION: 340
    CRAN: http://cran.rstudio.com

  - R_VERSION: oldrel
    RTOOLS_VERSION: 341
    CRAN: http://cran.rstudio.com

  - R_VERSION: oldrel
    RTOOLS_VERSION: 342
    CRAN: http://cran.rstudio.com

  - R_VERSION: oldrel
    RTOOLS_VERSION: 343
    CRAN: http://cran.rstudio.com

  - R_VERSION: devel
    GCC_PATH: mingw_32

matrix:
  fast_finish: true

build_script:
  - travis-tool.sh install_github ropensci/rrricanesdata
  - travis-tool.sh r_binary_install proto rgdal
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits

notifications:
 - provider: Email
   to:
     - tim.trice@gmail.com
   subject: 'rrricanes build {{status}}'
   message: "https://ci.appveyor.com/project/ropensci/rrricanes"
   on_build_success: false
   on_build_failure: true
   on_build_status_changed: true
